version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80"  # Порт для фронтенда
    networks:
      - app_network

  backend:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    expose:
      - "8000"  # Только внутри контейнера
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Порт для Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

